about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/urls.py
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = "posts.views.page_not_found" # noqa
handler500 = "posts.views.server_error" # noqa
urlpatterns = [
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls),
    path("", include("posts.urls")),
    path("about/", include("about.urls", namespace="about")),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )

templates/includes/author_card.html
<div class="col-md-3 mb-3 mt-1">
<div class="card">
    <div class="card-body">
            <div class="h2">
                <!-- Имя автора -->
                {{ author.get_full_name }}
            </div>
            <div class="h3 text-muted">
                 <!-- username автора -->
                 {{ author }}
            </div>
    </div>
    <ul class="list-group list-group-flush">
            <li class="list-group-item">
                    <div class="h6 text-muted">
                    Подписчиков: {{ followers }} <br />
                    Подписан: {{ follows }}
                    </div>
            </li>
            <li class="list-group-item">
                    <div class="h6 text-muted">
                        <!--Количество записей -->
                        Записей: {{ count }}
                    </div>
            </li>
            {% if is_user %}
                <li class="list-group-item">
                {% if following %}
                    <a class="btn btn-lg btn-light" href="{% url 'profile_unfollow' author.username %}" role="button">
                        Отписаться
                    </a>
                {% else %}
                    <a class="btn btn-lg btn-primary" href="{% url 'profile_follow' author.username %}" role="button">
                        Подписаться
                    </a>
                {% endif %}
                </li>
            {% endif %}
    </ul>
</div>
</div>

templates/includes/comments.html
{% load user_filters %}

{% if user.is_authenticated %}
<div class="card my-4">
    <form method="post" action="{% url 'add_comment' username=post.author.username post_id=post.id %}">
        {% csrf_token %}
        <h5 class="card-header">Добавить комментарий:</h5>
        <div class="card-body">
            <div class="form-group">
                {{ form.text|addclass:"form-control" }}
            </div>
            <button type="submit" class="btn btn-primary">Отправить</button>
        </div>
    </form>
</div>
{% endif %}

<!-- Комментарии -->
{% for item in comments %}
<div class="media card mb-4">
    <div class="media-body card-body">
        <h5 class="mt-0">
            <a href="{% url 'profile' item.author.username %}"
               name="comment_{{ item.id }}">
                {{ item.author.username }}
            </a>
        </h5>
        <p>{{ item.text|linebreaksbr }}</p>
        <small class="text-muted">{{ item.created }}</small>
    </div>
</div>
{% endfor %} 

templates/includes/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <p class="m-0 text-dark text-center ">
        <br><a href="{% url 'about:author' %}">Об авторе</a>
        <br><a href="{% url 'about:tech' %}">Технологии</a>
        {% url 'index' as index %}
        {% if request.path != index %}
            <br><a href="{{ index }}">Главная</a>
        {% endif %}
        
    </p>
    <p class="m-0 text-dark text-center ">Социальная сеть <span style="color:red">Ya</span>tube © {{ year }}, все права защищены.</p>
</footer>

templates/includes/menu.html
{% if user.is_authenticated %} 
<div class="row">
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link {% if index %}active{% endif %}" href="{% url 'index' %}">
                  Все авторы
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% if follow %}active{% endif %}" href="{% url 'follow_index' %}">
                Избранные авторы
            </a>
        </li>
    </ul>
</div>
{% endif %}

templates/includes/nav.html
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
    <a class="navbar-brand" href="{% url 'index' %}"><span style="color:red">Ya</span>tube</a>
    <nav class="my-2 my-md-0 mr-md-3">
        {% if user.is_authenticated %}
        Пользователь: {{ user.username }}.
        <a class="p-2 text-dark" href="{% url 'new_post' %}">Новая запись</a>
        <a class="p-2 text-dark" href="{% url 'password_change' %}">Изменить пароль</a>
        <a class="p-2 text-dark" href="{% url 'logout' %}">Выйти</a>
        {% else %}
        <a class="p-2 text-dark" href="{% url 'login' %}">Войти</a> |
        <a class="p-2 text-dark" href="{% url 'signup' %}">Регистрация</a>
        {% endif %}
    </nav>
</nav> 

templates/includes/paginator.html
{# Отрисовываем навигацию паджинатора только если есть и другие страницы #}
{% if page.has_other_pages %}
<nav>
  <ul class="pagination">
    {% if page.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.previous_page_number }}">&laquo; Предыдущая</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">&laquo; Предыдущая</span>
    </li>
    {% endif %}
    {% for i in page.paginator.page_range %}
    {% if page.number == i %}
    <li class="page-item active">
      <span class="page-link">{{ i }}
        <span class="sr-only">(текущая)</span>
      </span>
    </li>
    {% else %}
    <li class="page-item">
      <a class="page-link" href="?page={{ i }}">{{ i }}</a>
    </li>
    {% endif %}
    {% endfor %}
    {% if page.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.next_page_number }}">Следующая &raquo;</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">Следующая &raquo;</span>
    </li>
    {% endif %}
  </ul>
</nav>
{% endif %} 

templates/includes/post_card.html
<div class="card mb-3 mt-1 shadow-sm">
    {% load thumbnail %}
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img" src="{{ im.url }}">
    {% endthumbnail %}
        <div class="card-body">
            <p class="card-text">
                    <!-- Ссылка на страницу автора в атрибуте href; username автора в тексте ссылки -->
                    <h5><a href="{% url 'profile' post.author.username %}"><strong class="d-block text-gray-dark">{{ author }}</strong></a></h5>
                    <h5>
                        {% if post.group %}
                            Сообщество: <a href="{% url 'group' post.group.slug %}">{{ post.group }}</a> 
                        {% else %}
                            <i> &lt;нет группы&gt; </i>
                        {% endif %}
                    </h5>
                    <!-- Текст поста -->
                    <p>{{ post.text|linebreaksbr }}</p>
            </p>
            {% include "includes/post_footer.html" %}
        </div>
</div>

templates/includes/post_footer.html
<div class="d-flex justify-content-between align-items-center">
    <div class="btn-group ">
            <!-- Ссылка на страницу записи в атрибуте href-->
            <a class="btn btn-sm text-muted" href="{% url 'post' post.author.username post.id %}" role="button">Добавить комментарий</a>
            <!-- Ссылка на редактирование, показывается только автору записи -->
            {% if user.username == post.author.username %}
                <a class="btn btn-sm text-muted" href="{% url 'post_edit' post.author.username post.id %}" role="button">Редактировать</a>
            {% endif %}
    </div>
    {% include "includes/comments.html" %}
    <!-- Дата публикации  -->
    <small class="text-muted">Дата публикации: {{ post.pub_date|date:"d M Y" }},</small>
</div>

templates/includes/post_item.html
<div class="card mb-3 mt-1 shadow-sm">

    <!-- Отображение картинки -->
    {% load thumbnail %}
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img" src="{{ im.url }}" />
    {% endthumbnail %}
    <!-- Отображение текста поста -->
    <div class="card-body">
      <p class="card-text">
        <!-- Ссылка на автора через @ -->
        <a name="post_{{ post.id }}" href="{% url 'profile' post.author.username %}">
          <strong class="d-block text-gray-dark">@{{ post.author }}</strong>
        </a>
        {{ post.text|linebreaksbr }}
      </p>
  
      <!-- Если пост относится к какому-нибудь сообществу, то отобразим ссылку на него через # -->
      {% if post.group %}
      <a class="card-link muted" href="{% url 'group' post.group.slug %}">
        <strong class="d-block text-gray-dark">#{{ post.group.title }}</strong>
      </a>
      {% endif %}
  
      <!-- Отображение ссылки на комментарии -->
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
          {% if post.comments.exists %}
          <div>
            Комментариев: {{ post.comments.count }}
          </div>
          {% endif %}
          <a class="btn btn-sm btn-primary" href="{% url 'post' post.author.username post.id %}" role="button">
            Добавить комментарий
          </a>
  
          <!-- Ссылка на редактирование поста для автора -->
          {% if user == post.author %}
          <a class="btn btn-sm btn-info" href="{% url 'post_edit' post.author.username post.id %}" role="button">
            Редактировать
          </a>
          {% endif %}
        </div>
  
        <!-- Дата публикации поста -->
        <small class="text-muted">{{ post.pub_date }}</small>
      </div>
    </div>
</div> 